<a href="https://colab.research.google.com/github/liuguliu/study_notebook/blob/main/%E5%90%84%E7%A7%8D%E6%B5%8B%E8%AF%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
from torch.utils.data import TensorDataset, DataLoader
from torch.utils.data.dataset import random_split
import matplotlib.pyplot as plt
%matplotlib inline
import time
from scipy.optimize import curve_fit

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

# 使用nn.MaxPool2d进行最大池化
max_pool_layer = nn.MaxPool2d(kernel_size = 2, stride = 1)
x = torch.randn(2,4,4)
print(x)
output = max_pool_layer(x)
print(output)
print(output.shape)

tensor([[[ 1.2329,  0.6282, -0.9099,  0.1016],
         [ 0.4659, -0.6917, -1.0647, -0.2999],
         [ 0.6712, -1.1504, -0.7830, -0.2535],
         [-0.2884, -1.0061, -0.5499,  1.6950]],

        [[-1.3080,  0.7277, -1.3187,  0.1248],
         [-1.1521, -0.0276,  0.1870,  0.5437],
         [ 0.6590,  0.2797, -1.3010, -0.0504],
         [ 0.7964, -1.8424,  0.5715, -1.1471]]])
tensor([[[ 1.2329,  0.6282,  0.1016],
         [ 0.6712, -0.6917, -0.2535],
         [ 0.6712, -0.5499,  1.6950]],

        [[ 0.7277,  0.7277,  0.5437],
         [ 0.6590,  0.2797,  0.5437],
         [ 0.7964,  0.5715,  0.5715]]])
torch.Size([2, 3, 3])


In [ ]:
import torch
from torch import nn

input = torch.randn(3,4)
print("input:")
print(input)

label = torch.tensor([1,0,2])
torch.manual_seed(2)

loss = nn.CrossEntropyLoss()

loss_value = loss(input, label)
print(loss_value)

input:
tensor([[ 0.1715, -0.1502, -0.3124,  0.8229],
        [ 0.7275,  1.4131,  0.8456, -0.4947],
        [-0.9216, -1.6341,  1.5224,  1.3859]])
tensor(1.3159)


In [ ]:
import torch
from torch import nn

m = nn.LogSoftmax(dim=1)
loss = nn.NLLLoss()

input = torch.randn(3,5, requires_grad = True)
print("input:")
print(input)
target = torch.tensor([1,0,4])
mout = m(input)
print("mout:")
print(mout)
output = loss(mout, target)
print("output")
print(output)


input:
tensor([[ 0.6008,  0.1098, -0.8411, -0.2908, -0.1480],
        [-0.9266, -1.3256,  1.4205, -0.4190,  0.3577],
        [-0.1508,  0.1087, -0.1135, -1.3955, -1.3766]], requires_grad=True)
mout:
tensor([[-1.0048, -1.4958, -2.4467, -1.8964, -1.7536],
        [-2.8565, -3.2555, -0.5093, -2.3489, -1.5722],
        [-1.3650, -1.1055, -1.3277, -2.6097, -2.5909]],
       grad_fn=<LogSoftmaxBackward0>)
output
tensor(2.3144, grad_fn=<NllLossBackward0>)
